name: Test and deploy

## Actions that will be executed when you push code currently none
on:
    push:

## 2
jobs:
    ## 3
    unit_tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Unit tests
              with:
                  java-version: 1.8
            - name: Make gradlew executable
              run: chmod +x ./gradlew
            - name: Execute test
              run: ./gradlew test
    ## 4
    android_tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Instrumentation Tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                  api-level: 29
                  script: ./gradlew connectedAndroidTest